version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"  # local machine port : container port
    volumes:
    - /app/node_modules
    - .:/app
    stdin_open: true

  redis-server:
    image: 'redis'

